#pragma once

#define IDI_BESKTOP_APP 1001

#define IDR_BESKTOP_PACK_BASIC 101
#define IDR_BESKTOP_PACK_PLUS_COUPLE 201
#define IDR_BESKTOP_PACK_PLUS_FRIENDS 202
#define IDR_BESKTOP_PACK_PLUS_CREATOR 203
